config/routes.rb
Rails.application.routes.draw do
  devise_for :members
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :member
  validates :title, presence: true, length: { minimum: 2 }, allow_blank: false
  validates :body, presence: true, length: { maximum: 1000 }, allow_blank: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  def new
    @member = Member.new
  end

  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to members_path
    else
      render :new
    end
  end

  def index
    @members = Member.all
  end

  def show
    @member = Member.find(params[:id])
  end

  private

  def member_params
    params.require(:member).permit(:name, :password, :email)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_member!, only: %i[new create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_member.posts.build(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  <% if current_member %>  
      <%= link_to "Sign out", destroy_member_session_path, :method => :delete, class: "destroy_member_session" %>
    <%else%>
      <%= link_to "Sign up", new_member_registration_path,  class: "new_member_registration" %>
      <%= link_to "Login", new_member_session_path,  class: "new_member_session" %>
  <% end %>  
  </body>
</html>

app/views/posts/index.html.erb
<div class = "post-index center" > 
<h1>All Posts</h1>
<ul id="posts">
  <% @posts.each do |post| %>
  <% if current_member %>
          <p>Author: <%= post.member.name %></p>
        <% end %>
    <li>
      <%= link_to post.title, post_path(post) %>
    </li>
  <% end %>
</ul>
<%= link_to "Create a New Post", new_post_path, class: "new_post" %>
</div>

app/views/posts/new.html.erb
<div class = "center" >
<h1>CREATE A NEW POST</h1>
<%= form_for(@post) do |f| %>
  <ul>
  <% @post.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  Title <br /><%= f.text_field :title %><br /><br />
  Body <br /><%= f.text_area :body %><br /><br />
  <%= f.submit %>
<% end %>
</div>

app/views/posts/show.html.erb
<div class = "center" >
<h4><%= @post.title %></h4>
<p><%= @post.body %></p>
<% if current_member %>
          <p>Author: <%= post.member.name %></p>
        <% end %><%= link_to "<< Back to Post List", posts_path %>
<%= link_to "Create a New Post", new_post_path, class: "new_post" %>
</div>